name: Buf Linter
on:
  push:
  pull_request:
jobs:
  buf:
    name: buf-lint-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
